resilience4j.circuitbreaker:
    instances:
        TicketService:           
            failureRateThreshold: 50
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitDurationInOpenState: 60s
            automaticTransitionFromOpenToHalfOpenEnabled: true
  