spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CreditCardMS
          uri: lb://CreditCardMS
          predicates:
            - Path=/creditcard
        - id: FlightMS
          uri: lb://FlightMS
          predicates:
            - Path=/flights/**
        - id: PassengerMS
          uri: lb://PassengerMS
          predicates:
            - Path=/passenger/**
        - id: TicketMS
          uri: lb://TicketMS
          predicates:
            - Path=/book/**
        - id: UserMS
          uri: lb://UserMS
          predicates:
            - Path=/users/**
         
      
